### ISSUE TITLE
answer important questions 

### ISSUE THREAD

**Issue by bugbounted** [7x11x13/youtube-up#5]
Hi [7x11x13](https://github.com/7x11x13),

1. this code run headlessly , because i want to deploy it on cloud stack ?
2. which ip you test it , because on other than us region make multiply SAPISID in cookie.txt exported
3. from which exact url must get cookies.txt , means when visit youtube upload studio under the video tab on UPLOAD VIDEOS button, badge count number of Get cookies.txt LOCALLY changable to other pages under base domain equalled youtube.com or any other subdomains of it

waiting for your response 
finest regards

**Comment by bugbounted** [comment]
also getting below error on runtime :

```
C:\Users\Bugbounted\Desktop\New folder\New folder (2)>python test.py
Traceback (most recent call last):
  File "C:\Users\Bugbounted\Desktop\New folder\New folder (2)\test.py", line 11, in <module>
    uploader.upload("video.mp4", metadata)
  File "C:\Users\Bugbounted\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_up\uploader.py", line 166, in upload
    self._get_session_token()
  File "C:\Users\Bugbounted\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_up\uploader.py", line 271, in _get_session_token
    driver.get("https://youtube.com/upload")
  File "C:\Users\Bugbounted\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "C:\Users\Bugbounted\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Bugbounted\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Navigation timed out after 60000 ms
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5
TimeoutError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:740:5
bail@chrome://remote/content/marionette/sync.sys.mjs:211:19
```

**Comment by 7x11x13** [comment]
>     1. this code run headlessly , because i want to deploy it on cloud stack ?

Yes

>     2. which ip you test it , because on other than us region make multiply SAPISID in cookie.txt exported

From a residential American IP, you will likely be blocked running from a datacenter (just guessing, haven't tried it)

>     3. from which exact url must get cookies.txt , means when visit youtube upload studio under the video tab on UPLOAD VIDEOS button, badge count number of Get cookies.txt LOCALLY changable to other pages under base domain equalled youtube.com or any other subdomains of it

https://www.youtube.com
